import { Types } from "mongoose";

export type TMentorRegistration = {
  mentorId: Types.ObjectId;
  title?: string;
  fullName: string;
  preferredName: string;
  pronouns: string;
  contactNum: number;
  email: string;
  country: string;
  location: string;
  gender: string;
  about: string;
  reviewCount?: number;
  ratingCount?: number;
  introVideo?: string;
  industryExpertise: string;
  careerLavel: string;
  specializedSkill: string;
  mentoringStyle: string;
  education: string;
  mentorExperience: string;
  preferredDays: [string];
  availableTime?: string;
  startBreakTime: string;
  endBreakTime: string;
  startTime: string;
  endTime: string;
  status: 'pending' | 'accept' | 'cenceled';
  professionalCredential?: [string];
  additionalDocument?: [string];
};