name: Pro_Mentor_Backend CI/CD

on:
  push:
    branches: [ "main" ] 

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [ 22.x]
      
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present  
    - name: Add npm Global Binaries to PATH
      run: echo 'export PATH=$PATH:/home/masters/.npm-global/bin' >> $GITHUB_ENV
    - name: Change Directory
      run: cd /home/masters/actions-pro_mentor_backend/_work/pro_mentor_backend/pro_mentor_backend
    - name: Restart PM2
      run: /home/masters/.npm-global/bin/pm2 restart 0

